{"version":1,"ops":[{"type":6,"author":{"id":"d4ba99f16422e9377de56dab81d2b84415f00388"},"timestamp":1581570695,"metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdElzc3VlRWRpdDozNTA1ODY5MjI="},"target":"be28bf4a64c29931f39fba28c51260b2ac81fe95acd8f7fbe8448c8d17e380c7","message":"Then using the `exportlegends all` command it fails while doing the export.\n### Error message\n```\n~/df_linux/hack/scripts/exportlegends.lua:813: Cannot write field viewscreen_export_graphical_mapst.sel_idx: not found.\nstack traceback:\n\t[C]: in metamethod '__newindex'\n\t~/df_linux/hack/scripts/exportlegends.lua:813: in function \u003c~/df_linux/hack/scripts/exportlegends.lua:802\u003e\n```\n\n### Code inspection\nOpening the `exportlegends.lua` file it files in the function export_detailed_maps() (line 801-821):\n```\nfunction export_detailed_maps()\n    script.start(function()\n        for i = 1, #MAPS do\n            local vs = dfhack.gui.getViewscreenByType(df.viewscreen_export_graphical_mapst, 0)\n            if not vs then\n                local legends_vs = dfhack.gui.getViewscreenByType(df.viewscreen_legendsst, 0)\n                    or qerror(\"Could not find legends screen\")\n                gui.simulateInput(legends_vs, 'LEGENDS_EXPORT_DETAILED_MAP')\n            end\n\n            vs = dfhack.gui.getViewscreenByType(df.viewscreen_export_graphical_mapst, 0)\n                or qerror(\"Could not find map export screen\")\n            -- FAIL ON NEXT LINE --\n            vs.sel_idx = i - 1\n            -- FAIL ON LINE ABOVE --\n            print('    Exporting map: ' .. MAPS[i])\n            gui.simulateInput(vs, 'SELECT')\n            while dfhack.gui.getCurViewscreen() == vs do\n                script.sleep(10, 'frames')\n            end\n        end\n    end)\nend\n```\n### Quick fix\nI commented out line 813. So the old code was:\n```\n            vs = dfhack.gui.getViewscreenByType(df.viewscreen_export_graphical_mapst, 0)\n                or qerror(\"Could not find map export screen\")\n            vs.sel_idx = i - 1\n            print('    Exporting map: ' .. MAPS[i])\n```\nNew code:\n\n```\n            vs = dfhack.gui.getViewscreenByType(df.viewscreen_export_graphical_mapst, 0)\n                or qerror(\"Could not find map export screen\")\n            -- vs.sel_idx = i - 1\n            print('    Exporting map: ' .. MAPS[i])\n```\nThis fixed the problem for me and was able to export the maps after this.\nThis might have other implications but not familiar enough with this code to tell.\n(Note: Numbering of export files looks fine, not problems found)","files":null},{"type":3,"author":{"id":"e77d0a5f059ed8eaaa1afef6624480d02a2f025a"},"timestamp":1581561677,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDU4NTUyMTM3NA==","github-url":"https://github.com/DFHack/dfhack/issues/1494#issuecomment-585521374"},"message":"What DFHack version and OS are you using?","files":null},{"type":3,"author":{"id":"d4ba99f16422e9377de56dab81d2b84415f00388"},"timestamp":1581570592,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDU4NTU1MzY1Mw==","github-url":"https://github.com/DFHack/dfhack/issues/1494#issuecomment-585553653"},"message":"OS: Linux mint 19.1 (Linux - 4.15.0-58-generic - x86_64)\nDFHack version: Current dev: commit e9a295c788df1b32dff350951759ec82decdb0d0\nCC (compiler): cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0\nBuild it using compile instructions on: https://dfhack.readthedocs.io/en/latest/docs/Compile.html\nDF version: 0.47.02\n\nSo latest DFHack, lastest DF.\nBoth clean downloads (no mods or graphics or anything else)","files":null},{"type":3,"author":{"id":"df7feee793b3a4f60453609739052ef8e882d092"},"timestamp":1581594004,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDU4NTcwNjAyOA==","github-url":"https://github.com/DFHack/dfhack/issues/1494#issuecomment-585706028"},"message":"If I understand it correctly, the problem line selects which map to export, i.e. line in the list, and does a human-\u003eC index tranlation (1-based -\u003e 0-based). Your quick fix ought to result in all maps actually being the Standard biome+site map selection (as it's the default).\n\nComparing with 0.44.12, it seems the field sel_idx has gone missing and been replaced by anon_1 (probably by mistake). Changing which line is selected in the list changes the value of this field according. Thus, it seems to firstly be a df-structures issue (to clarify: it's not a matter of casting blame, but to forward a problem to its root).","files":null},{"type":5,"author":{"id":"e77d0a5f059ed8eaaa1afef6624480d02a2f025a"},"timestamp":1581608394,"metadata":{"github-id":"MDEyOkxhYmVsZWRFdmVudDMwMzUzNzk2OTA="},"added":["bug"],"removed":[]},{"type":5,"author":{"id":"e77d0a5f059ed8eaaa1afef6624480d02a2f025a"},"timestamp":1581608394,"metadata":{"github-id":"MDEyOkxhYmVsZWRFdmVudDMwMzUzNzk2OTM="},"added":["develop only"],"removed":[]},{"type":5,"author":{"id":"e77d0a5f059ed8eaaa1afef6624480d02a2f025a"},"timestamp":1581608394,"metadata":{"github-id":"MDEyOkxhYmVsZWRFdmVudDMwMzUzNzk2OTU="},"added":["structures"],"removed":[]},{"type":4,"author":{"id":"e77d0a5f059ed8eaaa1afef6624480d02a2f025a"},"timestamp":1581608407,"metadata":{"github-id":"MDExOkNsb3NlZEV2ZW50MzAzNTM4MDU1Nw=="},"status":2}]}