{"version":1,"ops":[{"type":1,"author":{"id":"d7add89209e2ce64c8ddb8b019901d5691507b59"},"timestamp":1451206308,"metadata":{"github-id":"MDU6SXNzdWUxMjM5Njg3MzY=","github-url":"https://github.com/DFHack/dfhack/issues/780","origin":"github"},"title":"[0.42.03-alpha1] exportlegends dies writing legends_plus","message":"I recently have created a new world in 0.42.03 (surprise!) with the listed DFHack and went immediately to legends mode to export all with DFHack, all was well until it got to the extra data.\n\nThe error thrown:\n\n\u003e .../the/path/to/exportlegends.lua:208: Cannot read field vector\u003ccreature_raw*\u003e,-1: index out of bounds\n\nLazy rendition of stack trace:\n\n\u003e export_more_legends_xml \u003e export_legends_info \u003e f _(main?)_\u003e dfhack.lua\n\nNot a damning bug by any means, but I figure a bit more documentation can't hurt.\nIf there is any more information I can provide, please ask.","files":null}]}