{"version":1,"ops":[{"type":1,"author":{"id":"979ced4c505c0cce502326063be4d48ff1ca8fd9"},"timestamp":1408354185,"metadata":{"github-id":"MDU6SXNzdWU0MDQ2OTUzOA==","github-url":"https://github.com/DFHack/dfhack/issues/292","origin":"github"},"title":"DFHack does throw exit 1 on start (sh -x inside)","message":"Running dfhack 40.08-r2 with Phoebus.\nThere pops up an error: \n\n![image](https://cloud.githubusercontent.com/assets/8477981/3949645/ee42c458-26b9-11e4-9e71-56f4e5c15218.png)\n\nsh -x df_linux/dfhack  \n++ dirname df_linux/dfhack                                                                                                                                                                                                                                                        \n- DF_DIR=df_linux  \n- cd df_linux  \n- export SDL_DISABLE_LOCK_KEYS=1\n- SDL_DISABLE_LOCK_KEYS=1\n- RC=.dfhackrc\n- '[' -r /home/user/.dfhackrc ']'\n- '[' -r ./.dfhackrc ']'\n  ++ stty -g\n- old_tty_settings=5500:5:bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0\n- export LD_LIBRARY_PATH=:./hack/libs:./hack\n- LD_LIBRARY_PATH=:./hack/libs:./hack\n- PRELOAD_LIB=./hack/libdfhack.so\n- case \"$1\" in\n- setarch i386 -R env LD_PRELOAD=./hack/libdfhack.so ./libs/Dwarf_Fortress\n- ret=1\n- stty 5500:5:bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0\n- echo -e '\\n'\n- '[' -n '' ']'\n- exit 1","files":null}]}